### ISSUE TITLE
I get an error when render tag is the first child element

### ISSUE THREAD

**Issue by nurullah** [magento/pagebuilder-docs#56]
**Describe the bug**
I followed the instructions in the [Content Types Create](https://devdocs.magento.com/page-builder/docs/content-types/create/introduction.html) documentation. But i don't see any visual templates in the page builder when i was drag and drop my new component. Then i look at the browser console and i saw warning in the picture.

**To Reproduce**
1. Complete the instructions Content Types Create documentation.
2. Go to 'Page Builder'
3. Drag and drop the new component to the page builder area
4. See there is no visual template

**Expected behavior**
Visual editing area where i can editing

**Screenshots**
![image](https://user-images.githubusercontent.com/10761479/191979458-8128d745-9cdc-4f07-a558-65fc4148d4ff.png)

**Comment by dshevtsov** [comment]
The content migrated to <https://developer.adobe.com/commerce/frontend-core/page-builder/content-types/create/>.
If the issues is still relevant, please feel free to reopen the issue in <https://github.com/AdobeDocs/commerce-frontend-core/issues>.
